### ISSUE TITLE
libyang packages for Ubuntu for ppc64le architecture

### ISSUE THREAD

**Issue by avmgithub** [opensourcerouting/libyang-debian#3]
hello,  I want to contribute to creating libyang package for Ubuntu for ppc64le architecture.  I was hoping someone from the community can help point me in the right direction on what I need to do to get .deb package in the download site for folks to download.  I appreciate your help.

**Comment by mwinter-osr** [comment]
I do believe this is already done as part of the official libyang package built for the Debian Buster (Debian 10) releases.
See https://packages.debian.org/buster/libs/libyang-cpp0.16
The Debian 10 binary packages should work unchanged on Ubuntu 14.04, 16.04 and 18.04 as well as Debian 8 and up (and probably others which I have not tested)

**Comment by avmgithub** [comment]
Thank you very much, I did not know built packages already existed. closing
